version: 1.0.{build}
image: Visual Studio 2019

environment:
  CoverityProjectToken:
    secure: BYP5qnptMazSCwTwgiFHlfqZd7BM3bwTRq2Cbs++ofg=
  CoverityNotificationEmail:
    secure: 0kyu0t8QwQYUQzqguVJP3N+VpEDfET2ArP+JNnOsUELJQvH8qbeQzPTM0ga0ek5G

install:

build_script:
  - make all

test_script:
  - dotnet test test/OpenRA.Test.dll --test-adapter-path:. --logger:Appveyor
after_test:
  - appveyor DownloadFile "https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP" -FileName IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
  - appveyor DownloadFile "https://raw.githubusercontent.com/wiki/OpenRA/OpenRA/Changelog.md" -FileName Changelog.md
  - make docs
  - ps: dir *.md | % {gc $_ -Raw | .\ConvertFrom-Markdown.ps1 | Out-File -FilePath "$($_.Name.TrimEnd(".md")).html"}
  - ps: (Get-Content "OpenRA.WindowsLauncher\ModConfig.cs.in").replace('DISPLAY_NAME', 'Red Alert').replace('MOD_ID', 'ra').replace('FAQ_URL', 'http://wiki.openra.net/FAQ') | Set-Content "OpenRA.WindowsLauncher\ModConfig.cs"
  - ps: dotnet build OpenRA.WindowsLauncher\OpenRA.WindowsLauncher.csproj -p:icon=RedAlert.ico --no-incremental
  - ps: Move-Item -Path OpenRA.WindowsLauncher.exe -Destination RedAlert.exe -Force
  - ps: (Get-Content "OpenRA.WindowsLauncher\ModConfig.cs.in").replace('DISPLAY_NAME', 'Tiberian Dawn').replace('MOD_ID', 'cnc').replace('FAQ_URL', 'http://wiki.openra.net/FAQ') | Set-Content "OpenRA.WindowsLauncher\ModConfig.cs"
  - ps: dotnet build OpenRA.WindowsLauncher\OpenRA.WindowsLauncher.csproj -p:icon=TiberianDawn.ico --force --no-incremental
  - ps: Move-Item -Path OpenRA.WindowsLauncher.exe -Destination TiberianDawn.exe -Force
  - ps: (Get-Content "OpenRA.WindowsLauncher\ModConfig.cs.in").replace('DISPLAY_NAME', 'Dune 2000').replace('MOD_ID', 'd2k').replace('FAQ_URL', 'http://wiki.openra.net/FAQ') | Set-Content "OpenRA.WindowsLauncher\ModConfig.cs"
  - ps: dotnet build OpenRA.WindowsLauncher\OpenRA.WindowsLauncher.csproj -p:icon=Dune2000.ico --force --no-incremental
  - ps: Move-Item -Path OpenRA.WindowsLauncher.exe -Destination Dune2000.exe -Force
  - ps: cp packaging\windows\OpenRA.ico .
  - ps: cp packaging\windows\RedAlert.ico .
  - ps: cp packaging\windows\TiberianDawn.ico .
  - ps: cp packaging\windows\Dune2000.ico .
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_COMMIT:~0,7%
  - '"C:\Program Files (x86)\NSIS\makensis.exe" /DSRCDIR="%APPVEYOR_BUILD_FOLDER%" /DTAG="git-%VERSION%" /DSUFFIX=" (dev)" /V3 packaging/windows/OpenRA.nsi'
  - move /Y %APPVEYOR_BUILD_FOLDER%\packaging\windows\OpenRA.Setup.exe %APPVEYOR_BUILD_FOLDER%\OpenRA-%VERSION%.exe

artifacts:
  - path: OpenRA-$(VERSION).exe
    name: Installer
  - path: coverity.zip
    name: Coverity Build
  - path: dupReport.html
    name: dupFinder Report
